# Generated by Django 2.1.1 on 2018-09-07 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('team1', models.CharField(max_length=3)),
                ('team2', models.CharField(max_length=3)),
                ('team3', models.CharField(max_length=3)),
                ('predicted_score', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Standing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week1', models.FloatField(default=0.0)),
                ('week2', models.FloatField(default=0.0)),
                ('week3', models.FloatField(default=0.0)),
                ('week4', models.FloatField(default=0.0)),
                ('week5', models.FloatField(default=0.0)),
                ('week6', models.FloatField(default=0.0)),
                ('week7', models.FloatField(default=0.0)),
                ('week8', models.FloatField(default=0.0)),
                ('week9', models.FloatField(default=0.0)),
                ('week10', models.FloatField(default=0.0)),
                ('week11', models.FloatField(default=0.0)),
                ('week12', models.FloatField(default=0.0)),
                ('week13', models.FloatField(default=0.0)),
                ('week14', models.FloatField(default=0.0)),
                ('week15', models.FloatField(default=0.0)),
                ('week16', models.FloatField(default=0.0)),
                ('week17', models.FloatField(default=0.0)),
                ('current_score', models.FloatField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='winspool.Player')),
            ],
        ),
    ]
