# Generated by Django 2.1.1 on 2018-09-07 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winspool', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NFLGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_team', models.CharField(max_length=3)),
                ('away_team', models.CharField(max_length=3)),
                ('game_id', models.IntegerField()),
                ('complete', models.IntegerField(default=0)),
                ('winner', models.CharField(max_length=3)),
            ],
        ),
    ]
