# Generated by Django 2.1.1 on 2018-09-09 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('winspool', '0002_nflgame'),
    ]

    operations = [
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('winning_teams', models.CharField(max_length=11)),
                ('week', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='standing',
            name='player',
        ),
        migrations.AddField(
            model_name='player',
            name='current_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.DeleteModel(
            name='Standing',
        ),
        migrations.AddField(
            model_name='week',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='winspool.Player'),
        ),
    ]
