# Generated by Django 2.1.1 on 2018-09-18 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winspool', '0003_auto_20180909_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='nflgame',
            name='season',
            field=models.IntegerField(default=2018),
        ),
        migrations.AddField(
            model_name='nflgame',
            name='week',
            field=models.IntegerField(default=0),
        ),
    ]
