#!/bin/bash

NAME="ffwinspool"
DJANGODIR=/opt/ffwinspool/ffwinspool
USER=ffwinspool
GROUP=ffwinspool
WORKERS=3
BIND=unix:/opt/ffwinsppol/run/gunicorn.sock
DJANGO_SETTINGS_MODULE=ffwinspool.settings
DJANGO_WSGI_MODULE=ffwinspool.wsgi
LOGLEVEL=error

cd $DJANGODIR
source production/bin/activate

export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DJANGODIR:$PYTHONPATH

exec production/bin/gunicorn ${DJANGO_WSGI_MODULE}:application \
  --name $NAME \
  --workers $WORKERS \
  --user=$USER \
  --group=$GROUP \
  --bind=$BIND \
  --log-level=$LOGLEVEL \
  --log-file=-
